<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dates {
	function __construct()
	   {
	      $this->CI = get_instance();
	   }

	function getSqlDate($indDate, $delimiter){
		$date = explode($delimiter, $indDate);
		return "$date[2]-$date[1]-$date[0]";
	}

}
