<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Middleware extends CI_Controller{
    function __construct()
    {
        parent::__construct();
    } 

    public function is_logged_in()
    {
        $user = $this->session->all_userdata();
        return isset($user);
    }

   
    
}
