<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Album_foto extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Album_foto_model');
    } 

    /*
     * Listing of album_foto
     */
    function index()
    {
        $data['album_foto'] = $this->Album_foto_model->get_all_album_foto();
        $data['content_name'] = "album_foto/index";
        $data['title_page'] = "Kategori Foto";
        // $data['option_button'][] = '<a href="'.site_url('album_foto/add').'" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Tambah Baru</a>';
        $this->load->view('index', $data);
    }

    /*
     * Adding a new album_foto
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_album','Nama Album','required');
		$this->form_validation->set_rules('tanggal_pembuatan','Tanggal Pembuatan','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_album' => $this->input->post('nama_album'),
				'tanggal_pembuatan' => $this->input->post('tanggal_pembuatan'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $album_foto_id = $this->Album_foto_model->add_album_foto($params);
            redirect('album_foto/index');
        }
        else
        {   
            $data['content_name'] = "album_foto/add";
            $data['title_page'] = "Tambah Album Foto";
            $this->load->view('index', $data);         
            
        }
    }  

    /*
     * Editing a album_foto
     */
    function edit($id)
    {   
        // check if the album_foto exists before trying to edit it
        $data['album_foto'] = $this->Album_foto_model->get_album_foto($id);
        
        if(isset($data['album_foto']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_album','Nama Album','required');
			$this->form_validation->set_rules('tanggal_pembuatan','Tanggal Pembuatan','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_album' => $this->input->post('nama_album'),
					'tanggal_pembuatan' => $this->input->post('tanggal_pembuatan'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Album_foto_model->update_album_foto($id,$params);            
                redirect('album_foto/index');
            }
            else
            {
                $data['_view'] = 'album_foto/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The album_foto you are trying to edit does not exist.');
    } 

    /*
     * Deleting album_foto
     */
    function remove($id)
    {
        $album_foto = $this->Album_foto_model->get_album_foto($id);

        // check if the album_foto exists before trying to delete it
        if(isset($album_foto['id']))
        {
            $this->Album_foto_model->delete_album_foto($id);
            redirect('album_foto/index');
        }
        else
            show_error('The album_foto you are trying to delete does not exist.');
    }
    
}
