<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Beritum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Beritum_model');
    } 

    /*
     * Listing of berita
     */
    function index()
    {
        $data['berita'] = $this->Beritum_model->get_all_berita();
        $data['content_name'] = "beritum/index";
        $data['title_page'] = "Master Berita";
        $data['option_button'][] = '<a href="'.site_url('beritum/add').'" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Tambah Baru</a>';
        $this->load->view('index', $data);
    }

    /*
     * Adding a new beritum
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('isi_berita','Isi Berita','required');
		$this->form_validation->set_rules('tanggal','Tanggal','required');
		$this->form_validation->set_rules('judul','Judul','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'kategori_id' => $this->input->post('kategori_id'),
				'status_aktif' => $this->input->post('status_aktif'),
				'judul' => $this->input->post('judul'),
				'tanggal' => $this->input->post('tanggal'),
				'isi_berita' => $this->input->post('isi_berita'),
            );
            
            $beritum_id = $this->Beritum_model->add_beritum($params);
            redirect('beritum/index');
        }
        else
        {
			$this->load->model('Master_kategori_model');
			$data['all_master_kategori'] = $this->Master_kategori_model->get_all_master_kategori();
            
            $data['_view'] = 'beritum/add';
            $data['content_name'] = "beritum/add";
            $data['title_page'] = "Tambah Berita";
            $this->load->view('index',$data);
        }
    }  

    /*
     * Editing a beritum
     */
    function edit($id)
    {   
        // check if the beritum exists before trying to edit it
        $data['beritum'] = $this->Beritum_model->get_beritum($id);
        
        if(isset($data['beritum']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('isi_berita','Isi Berita','required');
			$this->form_validation->set_rules('tanggal','Tanggal','required');
			$this->form_validation->set_rules('judul','Judul','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'kategori_id' => $this->input->post('kategori_id'),
					'status_aktif' => $this->input->post('status_aktif'),
					'judul' => $this->input->post('judul'),
					'tanggal' => $this->input->post('tanggal'),
					'isi_berita' => $this->input->post('isi_berita'),
                );

                $this->Beritum_model->update_beritum($id,$params);            
                redirect('beritum/index');
            }
            else
            {
				$this->load->model('Master_kategori_model');
				$data['all_master_kategori'] = $this->Master_kategori_model->get_all_master_kategori();

                $data['_view'] = 'beritum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The beritum you are trying to edit does not exist.');
    } 

    /*
     * Deleting beritum
     */
    function remove($id)
    {
        $beritum = $this->Beritum_model->get_beritum($id);

        // check if the beritum exists before trying to delete it
        if(isset($beritum['id']))
        {
            $this->Beritum_model->delete_beritum($id);
            redirect('beritum/index');
        }
        else
            show_error('The beritum you are trying to delete does not exist.');
    }
    
}
