<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Carousel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Carousel_model');
    } 

    /*
     * Listing of carousel
     */
    function index()
    {
        $data['carousel'] = $this->Carousel_model->get_all_carousel();
        
        $data['_view'] = 'carousel/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new carousel
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('judul','Judul','required');
		$this->form_validation->set_rules('nama_gambar','Nama Gambar','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'status' => $this->input->post('status'),
				'judul' => $this->input->post('judul'),
				'caption' => $this->input->post('caption'),
				'nama_gambar' => $this->input->post('nama_gambar'),
            );
            
            $carousel_id = $this->Carousel_model->add_carousel($params);
            redirect('carousel/index');
        }
        else
        {            
            $data['_view'] = 'carousel/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a carousel
     */
    function edit($id)
    {   
        // check if the carousel exists before trying to edit it
        $data['carousel'] = $this->Carousel_model->get_carousel($id);
        
        if(isset($data['carousel']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('judul','Judul','required');
			$this->form_validation->set_rules('nama_gambar','Nama Gambar','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'judul' => $this->input->post('judul'),
					'caption' => $this->input->post('caption'),
					'nama_gambar' => $this->input->post('nama_gambar'),
                );

                $this->Carousel_model->update_carousel($id,$params);            
                redirect('carousel/index');
            }
            else
            {
                $data['_view'] = 'carousel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The carousel you are trying to edit does not exist.');
    } 

    /*
     * Deleting carousel
     */
    function remove($id)
    {
        $carousel = $this->Carousel_model->get_carousel($id);

        // check if the carousel exists before trying to delete it
        if(isset($carousel['id']))
        {
            $this->Carousel_model->delete_carousel($id);
            redirect('carousel/index');
        }
        else
            show_error('The carousel you are trying to delete does not exist.');
    }
    
}
