<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        $record_pendaftaran = $this->db->get('pendaftaran')->result();
        $data['jumlah_haji']       = 0;
        $data['jumlah_umroh']      = 0;
        $data['jumlah_terhubungi'] = 0;
        $data['jumlah_blm_dihubungi'] = 0;
        foreach($record_pendaftaran as $value){
            if($value->status_kontak == "0")
                $data['jumlah_blm_dihubungi']++;
            if($value->status_kontak == "1")
                $data['jumlah_terhubungi']++;
            if($value->kategori_id == "1")
                $data['jumlah_haji']++;
            if($value->kategori_id == "2")
                $data['jumlah_umroh']++;
        }
        
        $data['content_name'] = "dashboard";
        $data['title_page'] = "Keluarga Besar Islam Haji Maulana Azhari";
        $this->load->view('index',$data);
    }
}
