<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Foto extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Foto_model');
    } 

    /*
     * Listing of foto
     */
    function index($album_id = null)
    {
        $data['foto'] = $this->Foto_model->get_all_foto_by_albumId($album_id);
        $data['content_name'] = "foto/index";
        $data['title_page'] = "Foto";
        $data['option_button'][] = '<a href="'.site_url('foto/add/'.$album_id).'" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> Tambah Baru</a>';
        $this->load->view('index',$data);
    }

    /*
     * Adding a new foto
     */
    function add($album_id = null)
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'album_id' => $this->input->post('album_id'),
				'nama_foto' => $this->input->post('nama_foto'),
				'caption' => $this->input->post('caption'),
            );
            
            $foto_id = $this->Foto_model->add_foto($params);

            $config['upload_path']          = './gambar/';
            $config['allowed_types']        = 'gif|jpg|png';
            $config['max_size']             = 2048;
            $config['file_name']            = $foto_id;

            $this->load->library('upload', $config);
         
            if ( ! $this->upload->do_upload('nama_gambar')){
                $error = array('error' => $this->upload->display_errors());
                print_r($error);
            }else{
                $data = array('upload_data' => $this->upload->data());
                $this->db->set('nama_gambar', $data['upload_data']['file_name']);
                $this->db->where('id', $foto_id);
                $this->db->update('foto'); 
                redirect('foto/index/'.$this->input->post('album_id'));
            }
        }
        else
        {            
            
            $data['content_name'] = "foto/add";
            $data['album_id'] = $album_id;
            $data['title_page'] = "Tambah Foto";
            $this->load->view('index',$data);
        }
    }  

    /*
     * Editing a foto
     */
    function edit($id)
    {   
        // check if the foto exists before trying to edit it
        $data['foto'] = $this->Foto_model->get_foto($id);
        
        if(isset($data['foto']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'album_id' => $this->input->post('album_id'),
					'nama_foto' => $this->input->post('nama_foto'),
					'caption' => $this->input->post('caption'),
					'tgl_update' => $this->input->post('tgl_update'),
					'nama_gambar' => $this->input->post('nama_gambar'),
                );

                $this->Foto_model->update_foto($id,$params);            
                redirect('foto/index');
            }
            else
            {
                $data['_view'] = 'foto/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The foto you are trying to edit does not exist.');
    } 

    /*
     * Deleting foto
     */
    function remove($id)
    {
        $foto = $this->Foto_model->get_foto($id);

        // check if the foto exists before trying to delete it
        if(isset($foto['id']))
        {
            $this->Foto_model->delete_foto($id);
            redirect('foto/index/'.$id);
        }
        else
            show_error('The foto you are trying to delete does not exist.');
    }

    function _uploadImage()
    {
        $config['upload_path']          = './upload/';
        $config['allowed_types']        = 'gif|jpg|png';
        $config['file_name']            = $this->product_id;
        $config['overwrite']            = true;
        $config['max_size']             = 2048; // 1MB
        // $config['max_width']            = 1024;
        // $config['max_height']           = 768;

        $this->load->library('upload', $config);

        if ($this->upload->do_upload('image')) {
            return $this->upload->data("file_name");
        }
        
        return "default.jpg";
    }
    
}
