<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        // $user = $this->session->all_userdata();
    
        // if(isset($user['username']))
        // 	redirect('dashboard');
        
    }

    function index()
    {
        $user = $this->session->all_userdata();
    
        if(isset($user['username']))
        	redirect('dashboard');
        else
            $this->load->view('login');
    }

    function do_login(){
    	//print_r($_POST);
    	//echo password_hash($_POST['password'], TRUE);

		$data=[];
		$userExist = $this->db
						  ->get_where('admin', array('username' => $_POST['username']));
		if($userExist->num_rows() > 0){
			$userExistData = $userExist->row_array();
			if(password_verify($_POST['password'],$userExistData['password'])){
				$this->session->set_userdata($userExistData);
				redirect('dashboard','refresh');				
			}
			else{
				$data['pesan'] = 'Kesalahan Pada Kombinasi Username dan Password';
				$this->session->set_flashdata($data);
				redirect("login");	
			}
		} 
		else{
			$data['pesan'] = 'Akun Anda Belum Terdaftar';
			$this->session->set_flashdata($data);
			redirect("login");
		}
		

    }
   public function logout()
	{
		$this->session->sess_destroy();
		redirect('/');
	}
}
