<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pesan_cusotmer extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pesan_cusotmer_model');
    } 

    /*
     * Listing of pesan_cusotmer
     */
    function index()
    {
        $data['pesan_cusotmer'] = $this->Pesan_cusotmer_model->get_all_pesan_cusotmer();
        
        $data['_view'] = 'pesan_cusotmer/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pesan_cusotmer
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required');
		$this->form_validation->set_rules('email','Email','valid_email');
		$this->form_validation->set_rules('subjek','Subjek','required');
		$this->form_validation->set_rules('isi_pesan','Isi Pesan','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
				'email' => $this->input->post('email'),
				'subjek' => $this->input->post('subjek'),
				'isi_pesan' => $this->input->post('isi_pesan'),
            );
            
            $pesan_cusotmer_id = $this->Pesan_cusotmer_model->add_pesan_cusotmer($params);
            redirect('pesan_cusotmer/index');
        }
        else
        {            
            $data['_view'] = 'pesan_cusotmer/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pesan_cusotmer
     */
    function edit($id)
    {   
        // check if the pesan_cusotmer exists before trying to edit it
        $data['pesan_cusotmer'] = $this->Pesan_cusotmer_model->get_pesan_cusotmer($id);
        
        if(isset($data['pesan_cusotmer']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required');
			$this->form_validation->set_rules('email','Email','valid_email');
			$this->form_validation->set_rules('subjek','Subjek','required');
			$this->form_validation->set_rules('isi_pesan','Isi Pesan','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'email' => $this->input->post('email'),
					'subjek' => $this->input->post('subjek'),
					'isi_pesan' => $this->input->post('isi_pesan'),
                );

                $this->Pesan_cusotmer_model->update_pesan_cusotmer($id,$params);            
                redirect('pesan_cusotmer/index');
            }
            else
            {
                $data['_view'] = 'pesan_cusotmer/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pesan_cusotmer you are trying to edit does not exist.');
    } 

    /*
     * Deleting pesan_cusotmer
     */
    function remove($id)
    {
        $pesan_cusotmer = $this->Pesan_cusotmer_model->get_pesan_cusotmer($id);

        // check if the pesan_cusotmer exists before trying to delete it
        if(isset($pesan_cusotmer['id']))
        {
            $this->Pesan_cusotmer_model->delete_pesan_cusotmer($id);
            redirect('pesan_cusotmer/index');
        }
        else
            show_error('The pesan_cusotmer you are trying to delete does not exist.');
    }
    
}
