<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Agenda_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get agenda by id
     */
    function get_agenda($id)
    {
        return $this->db->get_where('agenda',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all agenda
     */
    function get_all_agenda()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('agenda')->result_array();
    }
        
    /*
     * function to add new agenda
     */
    function add_agenda($params)
    {
        $this->db->insert('agenda',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update agenda
     */
    function update_agenda($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('agenda',$params);
    }
    
    /*
     * function to delete agenda
     */
    function delete_agenda($id)
    {
        return $this->db->delete('agenda',array('id'=>$id));
    }
}
