<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Album_foto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get album_foto by id
     */
    function get_album_foto($id)
    {
        return $this->db->get_where('album_foto',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all album_foto
     */
    function get_all_album_foto()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('album_foto')->result_array();
    }
        
    /*
     * function to add new album_foto
     */
    function add_album_foto($params)
    {
        $this->db->insert('album_foto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update album_foto
     */
    function update_album_foto($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('album_foto',$params);
    }
    
    /*
     * function to delete album_foto
     */
    function delete_album_foto($id)
    {
        return $this->db->delete('album_foto',array('id'=>$id));
    }
}
