<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Beritum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get beritum by id
     */
    function get_beritum($id)
    {
        return $this->db->get_where('berita',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all berita
     */
    function get_all_berita()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('berita')->result_array();
    }
        
    /*
     * function to add new beritum
     */
    function add_beritum($params)
    {
        $this->db->insert('berita',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update beritum
     */
    function update_beritum($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('berita',$params);
    }
    
    /*
     * function to delete beritum
     */
    function delete_beritum($id)
    {
        return $this->db->delete('berita',array('id'=>$id));
    }
}
