<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Carousel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get carousel by id
     */
    function get_carousel($id)
    {
        return $this->db->get_where('carousel',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all carousel
     */
    function get_all_carousel()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('carousel')->result_array();
    }
        
    /*
     * function to add new carousel
     */
    function add_carousel($params)
    {
        $this->db->insert('carousel',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update carousel
     */
    function update_carousel($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('carousel',$params);
    }
    
    /*
     * function to delete carousel
     */
    function delete_carousel($id)
    {
        return $this->db->delete('carousel',array('id'=>$id));
    }
}
