<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Foto_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get foto by id
     */
    function get_foto($id)
    {
        return $this->db->get_where('foto',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all foto
     */
    function get_all_foto()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('foto')->result_array();
    }        
    /*
     * Get all foto
     */
    function get_all_foto_by_albumId($album_id)
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('album_id', $album_id);
        return $this->db->get('foto')->result_array();
    }
        
    /*
     * function to add new foto
     */
    function add_foto($params)
    {
        $this->db->insert('foto',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update foto
     */
    function update_foto($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('foto',$params);
    }
    
    /*
     * function to delete foto
     */
    function delete_foto($id)
    {
        return $this->db->delete('foto',array('id'=>$id));
    }
}
