<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Master_kategori_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get master_kategori by id
     */
    function get_master_kategori($id)
    {
        return $this->db->get_where('master_kategori',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all master_kategori
     */
    function get_all_master_kategori()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('master_kategori')->result_array();
    }
        
    /*
     * function to add new master_kategori
     */
    function add_master_kategori($params)
    {
        $this->db->insert('master_kategori',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update master_kategori
     */
    function update_master_kategori($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('master_kategori',$params);
    }
    
    /*
     * function to delete master_kategori
     */
    function delete_master_kategori($id)
    {
        return $this->db->delete('master_kategori',array('id'=>$id));
    }
}
