<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pesan_cusotmer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pesan_cusotmer by id
     */
    function get_pesan_cusotmer($id)
    {
        return $this->db->get_where('pesan_cusotmer',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all pesan_cusotmer
     */
    function get_all_pesan_cusotmer()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('pesan_cusotmer')->result_array();
    }
        
    /*
     * function to add new pesan_cusotmer
     */
    function add_pesan_cusotmer($params)
    {
        $this->db->insert('pesan_cusotmer',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pesan_cusotmer
     */
    function update_pesan_cusotmer($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('pesan_cusotmer',$params);
    }
    
    /*
     * function to delete pesan_cusotmer
     */
    function delete_pesan_cusotmer($id)
    {
        return $this->db->delete('pesan_cusotmer',array('id'=>$id));
    }
}
